In [1]:
import pandas as pd

In [2]:
df_uber = pd.read_parquet('Drafts/df_uber_parquet.parquet')

In [3]:
df_uber.columns

Index(['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime',
       'passenger_count', 'trip_distance', 'pickup_longitude',
       'pickup_latitude', 'RatecodeID', 'store_and_fwd_flag',
       'dropoff_longitude', 'dropoff_latitude', 'payment_type', 'fare_amount',
       'extra', 'mta_tax', 'tip_amount', 'tolls_amount',
       'improvement_surcharge', 'total_amount'],
      dtype='object')

In [4]:
Dim_Payment = df_uber[['payment_type']].drop_duplicates().copy()

In [5]:
Dim_Payment

      payment_type
0                1
6                2
7                3
6585             4

In [6]:
Dim_Payment['payment_type_name'] = Dim_Payment['payment_type'].map({
    1:'Credit Card',
    2:'Cash',
    3:'No Charge',
    4:'Dispute',
    5:'Unknown',
    6:'Voided Trip'
})

In [7]:
Dim_Payment

      payment_type payment_type_name
0                1       Credit Card
6                2              Cash
7                3         No Charge
6585             4           Dispute

In [8]:
Dim_Payment.to_parquet('Final/Dim_Payment.parquet',index=False)