In [1]:
import pandas as pd

In [2]:
df_uber = pd.read_parquet('Drafts/df_uber_parquet.parquet')

In [3]:
df_uber.columns

Index(['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime',
       'passenger_count', 'trip_distance', 'pickup_longitude',
       'pickup_latitude', 'RatecodeID', 'store_and_fwd_flag',
       'dropoff_longitude', 'dropoff_latitude', 'payment_type', 'fare_amount',
       'extra', 'mta_tax', 'tip_amount', 'tolls_amount',
       'improvement_surcharge', 'total_amount'],
      dtype='object')

In [4]:
Dim_Rate = df_uber[['RatecodeID']].drop_duplicates().copy()

In [5]:
Dim_Rate

       RatecodeID
0               1
4               3
18              2
129             5
4664            4
74006           6

In [6]:
Dim_Rate = Dim_Rate.rename(columns={'RatecodeID':'rate_code_id'})

In [7]:
Dim_Rate['rate_code_name'] = Dim_Rate['rate_code_id'].map({
    1: 'Standard Rate',
    2: 'JFK Airport Flat Fare',
    3: 'Newark Airport',
    4: 'Nassau / Westchester',
    5: 'Negotiated Fare',
    6: 'Group Ride'
})

In [8]:
Dim_Rate

       rate_code_id         rate_code_name
0                 1          Standard Rate
4                 3         Newark Airport
18                2  JFK Airport Flat Fare
129               5        Negotiated Fare
4664              4   Nassau / Westchester
74006             6             Group Ride

In [9]:
Dim_Rate.to_parquet('Final/Dim_Rate.parquet',index=False)